### ISSUE TITLE
Kustomize version v3.8.7 does not exist

### ISSUE THREAD

**Issue by moziliar** [furiko-io/furiko#80]
When installing with `make`

**Comment by irvinlim** [comment]
Hi @moziliar thanks for the interest in the project!

I am able to install `kustomize` version 3.8.7 using the Makefile on my local machine. Perhaps this is related to Go environment (e.g. Go version or GOARCH)?

![image](https://user-images.githubusercontent.com/9884746/170866114-bcf744f6-98fd-4209-b6a0-d8596db6a1da.png)

One way to get around this is to just simply to download it into `./bin/kustomize` and the Makefile will not complain.

**Comment by irvinlim** [comment]
Closing because cannot replicate.

**Comment by irvinlim** [comment]
@moziliar We have updated to Kustomize v4.5.5, it should work on arm64 now :)
